/**
 * Hardcoded configuration constants
 * @module config/hardcoded
 */

export const FALLBACK_API_URL = 'https://anyparserapi.com'

export const OCR_PRESETS = Object.freeze({
  DOCUMENT: 'document',
  HANDWRITING: 'handwriting',
  SCAN: 'scan',
  RECEIPT: 'receipt',
  MAGAZINE: 'magazine',
  INVOICE: 'invoice',
  BUSINESS_CARD: 'business-card',
  PASSPORT: 'passport',
  DRIVER_LICENSE: 'driver-license'
} as const)

export const OCR_LANGUAGES = Object.freeze({
  AFRIKAANS: 'afr',
  AMHARIC: 'amh',
  ARABIC: 'ara',
  ASSAMESE: 'asm',
  AZERBAIJANI: 'aze',
  AZERBAIJANI_CYRILLIC: 'aze_cyrl',
  BELARUSIAN: 'bel',
  BENGALI: 'ben',
  TIBETAN: 'bod',
  BOSNIAN: 'bos',
  BRETON: 'bre',
  BULGARIAN: 'bul',
  CATALAN: 'cat',
  CEBUANO: 'ceb',
  CZECH: 'ces',
  SIMPLIFIED_CHINESE: 'chi_sim',
  SIMPLIFIED_CHINESE_VERTICAL: 'chi_sim_vert',
  TRADITIONAL_CHINESE: 'chi_tra',
  TRADITIONAL_CHINESE_VERTICAL: 'chi_tra_vert',
  CHEROKEE: 'chr',
  CORSICAN: 'cos',
  WELSH: 'cym',
  DANISH: 'dan',
  DANISH_FRAKTUR: 'dan_frak',
  GERMAN: 'deu',
  GERMAN_FRAKTUR: 'deu_frak',
  GERMAN_LATIN: 'deu_latf',
  DIVESH: 'div',
  DZONGKHA: 'dzo',
  GREEK: 'ell',
  ENGLISH: 'eng',
  MIDDLE_ENGLISH: 'enm',
  ESPERANTO: 'epo',
  EQUATORIAL_GUINEAN: 'equ',
  ESTONIAN: 'est',
  BASQUE: 'eus',
  FAROESE: 'fao',
  PERSIAN: 'fas',
  FILIPINO: 'fil',
  FINNISH: 'fin',
  FRENCH: 'fra',
  OLD_FRENCH: 'frm',
  FRISIAN: 'fry',
  SCOTTISH_GAELIC: 'gla',
  IRISH: 'gle',
  GALICIAN: 'glg',
  ANCIENT_GREEK: 'grc',
  GUJARATI: 'guj',
  HAITIAN_CREOLE: 'hat',
  HEBREW: 'heb',
  HINDI: 'hin',
  CROATIAN: 'hrv',
  HUNGARIAN: 'hun',
  ARMENIAN: 'hye',
  IGBO: 'iku',
  INDONESIAN: 'ind',
  ICELANDIC: 'isl',
  ITALIAN: 'ita',
  OLD_ITALIAN: 'ita_old',
  JAVANESE: 'jav',
  JAPANESE: 'jpn',
  JAPANESE_VERTICAL: 'jpn_vert',
  KANNADA: 'kan',
  GEORGIAN: 'kat',
  OLD_GEORGIAN: 'kat_old',
  KAZAKH: 'kaz',
  KHMER: 'khm',
  KIRGHIZ: 'kir',
  KURDISH: 'kmr',
  KOREAN: 'kor',
  KOREAN_VERTICAL: 'kor_vert',
  LAO: 'lao',
  LATIN: 'lat',
  LATVIAN: 'lav',
  LITHUANIAN: 'lit',
  LUXEMBOURGISH: 'ltz',
  MALAYALAM: 'mal',
  MARATHI: 'mar',
  MACEDONIAN: 'mkd',
  MALTESE: 'mlt',
  MONGOLIAN: 'mon',
  MAORI: 'mri',
  MALAY: 'msa',
  MYANMAR: 'mya',
  NEPALI: 'nep',
  DUTCH: 'nld',
  NORWEGIAN: 'nor',
  OCCITAN: 'oci',
  ODISHA: 'ori',
  OSD: 'osd',
  PUNJABI: 'pan',
  POLISH: 'pol',
  PORTUGUESE: 'por',
  PASHTO: 'pus',
  QUECHUA: 'que',
  ROMANIAN: 'ron',
  RUSSIAN: 'rus',
  SANSKRIT: 'san',
  SINHALA: 'sin',
  SLOVAK: 'slk',
  SLOVAK_FRAKTUR: 'slk_frak',
  SLOVENIAN: 'slv',
  SINDHI: 'snd',
  SPANISH: 'spa',
  OLD_SPANISH: 'spa_old',
  ALBANIAN: 'sqi',
  SERBIAN: 'srp',
  SERBIAN_LATIN: 'srp_latn',
  SUNDIANESE: 'sun',
  SWAHILI: 'swa',
  SWEDISH: 'swe',
  SYRIAC: 'syr',
  TAMIL: 'tam',
  TATAR: 'tat',
  TELUGU: 'tel',
  TAJIK: 'tgk',
  TAGALOG: 'tgl',
  THAI: 'tha',
  TIGRINYA: 'tir',
  TONGAN: 'ton',
  TURKISH: 'tur',
  UIGHUR: 'uig',
  UKRAINIAN: 'ukr',
  URDU: 'urd',
  UZBEK: 'uzb',
  UZBEK_CYRILLIC: 'uzb_cyrl',
  VIETNAMESE: 'vie',
  YIDDISH: 'yid',
  YORUBA: 'yor'
} as const)

export type OcrPresetType = (typeof OCR_PRESETS)[keyof typeof OCR_PRESETS]
export type OcrLanguageType = (typeof OCR_LANGUAGES)[keyof typeof OCR_LANGUAGES]
